new Swiper(".swiper.dress-head", {
    preloadImages: false,
    lazy: true,
    slidesPerView: 1,
    spaceBetween: 50,
    autoHeight: true,
    resizeObserver: true,
    speed: 200,
    allowSlideNext: true,
    allowSlidePrev: true,
    centeredSlides: false,
    centerInsufficientSlides: true,
    centeredSlidesBounds: true,
    loop: true,
    grabCursor: false,
    simulateTouch: false,
    autoplay: false,
    navigation: {
        nextEl: '.swiper-button-next.dress-head',
        prevEl: '.swiper-button-prev.dress-head',
    },
    allowTouchMove: true,
    preventClicks: true,
});

new Swiper(".swiper.dress-body", {
    preloadImages: false,
    lazy: true,
    slidesPerView: 1,
    spaceBetween: 50,
    autoHeight: true,
    resizeObserver: true,
    speed: 200,
    allowSlideNext: true,
    allowSlidePrev: true,
    centeredSlides: false,
    centerInsufficientSlides: true,
    centeredSlidesBounds: true,
    loop: true,
    grabCursor: false,
    simulateTouch: false,
    autoplay: false,
    navigation: {
        nextEl: '.swiper-button-next.dress-body',
        prevEl: '.swiper-button-prev.dress-body',
    },
    allowTouchMove: true,
    preventClicks: true,
});

new Swiper(".swiper.dress-bg", {
    preloadImages: false,
    lazy: true,
    slidesPerView: 1,
    spaceBetween: 50,
    autoHeight: true,
    resizeObserver: true,
    speed: 200,
    allowSlideNext: true,
    allowSlidePrev: true,
    centeredSlides: false,
    centerInsufficientSlides: true,
    centeredSlidesBounds: true,
    loop: true,
    grabCursor: false,
    simulateTouch: false,
    autoplay: false,
    navigation: {
        nextEl: '.swiper-button-next.dress-bg',
        prevEl: '.swiper-button-prev.dress-bg',
    },
    allowTouchMove: true,
    preventClicks: true,
});

new Swiper(".swiper.dress-eyes", {
    preloadImages: false,
    lazy: true,
    slidesPerView: 1,
    spaceBetween: 50,
    autoHeight: true,
    resizeObserver: true,
    speed: 200,
    allowSlideNext: true,
    allowSlidePrev: true,
    centeredSlides: false,
    centerInsufficientSlides: true,
    centeredSlidesBounds: true,
    loop: true,
    grabCursor: false,
    simulateTouch: false,
    autoplay: false,
    navigation: {
        nextEl: '.swiper-button-next.dress-eyes',
        prevEl: '.swiper-button-prev.dress-eyes',
    },
    allowTouchMove: true,
    preventClicks: true,
});


new Swiper(".swiper.dress-mouth", {
    preloadImages: false,
    lazy: true,
    slidesPerView: 1,
    spaceBetween: 50,
    autoHeight: true,
    resizeObserver: true,
    speed: 200,
    allowSlideNext: true,
    allowSlidePrev: true,
    centeredSlides: false,
    centerInsufficientSlides: true,
    centeredSlidesBounds: true,
    loop: true,
    grabCursor: false,
    simulateTouch: false,
    autoplay: false,
    navigation: {
        nextEl: '.swiper-button-next.dress-mouth',
        prevEl: '.swiper-button-prev.dress-mouth',
    },
    allowTouchMove: true,
    preventClicks: true,
});

new Swiper(".swiper.dress-clothes", {
    preloadImages: false,
    lazy: true,
    slidesPerView: 1,
    spaceBetween: 50,
    autoHeight: true,
    resizeObserver: true,
    speed: 200,
    allowSlideNext: true,
    allowSlidePrev: true,
    centeredSlides: false,
    centerInsufficientSlides: true,
    centeredSlidesBounds: true,
    loop: true,
    grabCursor: false,
    simulateTouch: false,
    autoplay: false,
    navigation: {
        nextEl: '.swiper-button-next.dress-clothes',
        prevEl: '.swiper-button-prev.dress-clothes',
    },
    allowTouchMove: true,
    preventClicks: true,
});
